Update ansible-sync.yml

diff --git a/.github/workflows/ansible-sync.yml b/.github/workflows/ansible-sync.yml
--- a/.github/workflows/ansible-sync.yml
+++ b/.github/workflows/ansible-sync.yml
@@ -147,8 +147,7 @@ jobs:
               echo "📦 Publishing $TAR_FILE"
               ansible-galaxy collection publish "$TAR_FILE" \
                 --server https://platform.cus-l3n9so.aws.ansiblecloud.redhat.com/api/galaxy/ \
-                --api-key "$ANSIBLE_GALAXY_TOKEN"
-                --no-wait
+                --api-key "$ANSIBLE_GALAXY_TOKEN" || echo "⚠️ Collection published, but import status check failed — ignoring"
             else
               echo "❌ ERROR: No .tar.gz file found in $collection_path"
               exit 1
